# Generated by Django 4.2 on 2023-04-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='hackathon',
            new_name='hackathon_id',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='user',
            new_name='user_id',
        ),
    ]
