# Generated by Django 4.2 on 2023-05-01 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrollments', '0003_rename_hackathon_id_enrollment_hackathon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_enrollment', to=settings.AUTH_USER_MODEL),
        ),
    ]
