# Generated by Django 4.2 on 2023-04-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathon',
            old_name='user_id',
            new_name='organization',
        ),
    ]
