# Generated by Django 4.2 on 2023-04-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='background_image',
            field=models.ImageField(default='default/no_image.jpg', max_length=255, upload_to='hackathons/bg_imgs/'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='hackathon_image',
            field=models.ImageField(default='default/no_image.jpg', max_length=255, upload_to='hackathons/hack/'),
        ),
    ]
