# Generated by Django 4.2 on 2023-04-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0002_alter_hackathon_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
