# Generated by Django 4.2 on 2023-04-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0003_alter_hackathon_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathon',
            old_name='user',
            new_name='user_id',
        ),
    ]
