# Generated by Django 4.2 on 2023-04-22 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackathons', '0001_initial'),
        ('enrollments', '0002_alter_enrollment_registration_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('type_of_submission', models.CharField(default='LINK', max_length=4)),
                ('image_submission', models.ImageField(max_length=255, null=True, upload_to='hackathon_submission/images/')),
                ('file_submission', models.FileField(max_length=255, null=True, upload_to='hackathon_submission/files/')),
                ('link_submission', models.URLField(null=True)),
                ('submission_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_favourite', models.BooleanField(default=False)),
                ('enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollments.enrollment')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons.hackathon')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
