# Generated by Django 4.2 on 2023-04-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_rename_hackathon_submission_hackathon_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='enrollment_id',
            new_name='enrollment',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='hackathon_id',
            new_name='hackathon',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='user_id',
            new_name='user',
        ),
    ]
