# Generated by Django 4.2 on 2023-05-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_rename_enrollment_id_submission_enrollment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='type_of_submission',
            new_name='submission_type',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='file_submission',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='image_submission',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='link_submission',
        ),
        migrations.AddField(
            model_name='submission',
            name='submission',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
