# Generated by Django 4.2 on 2023-05-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_rename_type_of_submission_submission_submission_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission',
            field=models.FileField(max_length=255, null=True, upload_to=''),
        ),
    ]
