# Generated by Django 4.2 on 2023-05-01 18:00

from django.db import migrations, models
import submissions.models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_alter_submission_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission',
            field=models.FileField(max_length=255, null=True, upload_to=submissions.models.submission_path),
        ),
    ]
