# Generated by Django 4.2 on 2023-05-01 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_alter_submission_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission',
            field=models.CharField(max_length=255, validators=[django.core.validators.URLValidator(), django.core.validators.FileExtensionValidator(['jpg', 'png', 'gif', 'pdf', 'docx', 'txt'])]),
        ),
    ]
